"$schema" = 'https://starship.rs/config-schema.json'

# Main Left Prompt
format = """
[](fg:#92cef5)\
$username\
[](fg:#92cef5 bg:#ccc1e9)\
$directory\
[](fg:#ccc1e9 bg:#41484d)\
$git_branch\
$git_status\
[](fg:#41484d bg:#b6c9d8)\
$c$rust$golang$nodejs$java$python\
[](fg:#b6c9d8)\
$line_break$character"""

# Right Prompt: Command Duration
right_format = """$cmd_duration"""

[username]
show_always = true
style_user = "bg:#92cef5 fg:#00344b"
style_root = "bg:#ffb4ab fg:#690005"
format = '[ $user ]($style)'

[directory]
style = "bg:#ccc1e9 fg:#332c4b"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "  "
style = "bg:#41484d fg:#c1c7ce"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#41484d fg:#ffb4ab"
format = '[$all_status$ahead_behind]($style)'

[cmd_duration]
min_time = 0
show_milliseconds = false
style = "fg:#d2e5f4 bg:#374955"
format = '[](fg:#374955)[ 󱎫 $duration ]($style)[](fg:#374955)'

# Language Modules
[nodejs]
symbol = "  nodejs"
style = "bg:#b6c9d8 fg:#21323e"
format = '[$symbol]($style)'

[c]
symbol = "  c"
style = "bg:#b6c9d8 fg:#21323e"
format = '[$symbol]($style)'

[rust]
symbol = "  rust"
style = "bg:#b6c9d8 fg:#21323e"
format = '[$symbol]($style)'

[golang]
symbol = "  golang"
style = "bg:#b6c9d8 fg:#21323e"
format = '[$symbol]($style)'

[python]
symbol = "  python"
style = "bg:#b6c9d8 fg:#21323e"
format = '[$symbol]($style)'

[java]
symbol = "  java"
style = "bg:#b6c9d8 fg:#21323e"
format = '[$symbol]($style)'

[character]
success_symbol = '[ ](bold fg:#92cef5)'
error_symbol = '[ ](bold fg:#ffb4ab)'
