"$schema" = 'https://starship.rs/config-schema.json'

# Main Left Prompt
format = """
[](fg:#afc6ff)\
$username\
[](fg:#afc6ff bg:#dfbbde)\
$directory\
[](fg:#dfbbde bg:#44474f)\
$git_branch\
$git_status\
[](fg:#44474f bg:#bfc6dc)\
$c$rust$golang$nodejs$java$python\
[](fg:#bfc6dc)\
$line_break$character"""

# Right Prompt: Command Duration
right_format = """$cmd_duration"""

[username]
show_always = true
style_user = "bg:#afc6ff fg:#132f60"
style_root = "bg:#ffb4ab fg:#690005"
format = '[ $user ]($style)'

[directory]
style = "bg:#dfbbde fg:#402843"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "  "
style = "bg:#44474f fg:#c5c6d0"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#44474f fg:#ffb4ab"
format = '[$all_status$ahead_behind]($style)'

[cmd_duration]
min_time = 0
show_milliseconds = false
style = "fg:#dbe2f9 bg:#3f4759"
format = '[](fg:#3f4759)[ 󱎫 $duration ]($style)[](fg:#3f4759)'

# Language Modules
[nodejs]
symbol = "  nodejs"
style = "bg:#bfc6dc fg:#293041"
format = '[$symbol]($style)'

[c]
symbol = "  c"
style = "bg:#bfc6dc fg:#293041"
format = '[$symbol]($style)'

[rust]
symbol = "  rust"
style = "bg:#bfc6dc fg:#293041"
format = '[$symbol]($style)'

[golang]
symbol = "  golang"
style = "bg:#bfc6dc fg:#293041"
format = '[$symbol]($style)'

[python]
symbol = "  python"
style = "bg:#bfc6dc fg:#293041"
format = '[$symbol]($style)'

[java]
symbol = "  java"
style = "bg:#bfc6dc fg:#293041"
format = '[$symbol]($style)'

[character]
success_symbol = '[ ](bold fg:#afc6ff)'
error_symbol = '[ ](bold fg:#ffb4ab)'
